version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.docker

  web: # Backend Service
    build: .
    command: >
      sh -c "python manage.py migrate &&
             gunicorn ulibrary_api.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env          # Loads base config (like SECRET_KEY)
      - .env.docker   # Overrides DB settings for Docker
    depends_on:
      - db

  frontend: # Frontend Service
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - web

volumes:
  postgres_data: